# Generated by Django 4.0.5 on 2022-06-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='reports')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('toShow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=64)),
                ('status', models.TextField(blank=True, null=True)),
                ('date_submit', models.DateField()),
                ('date_approve', models.DateField(blank=True, null=True)),
                ('file_report', models.FileField(blank=True, max_length=200, null=True, upload_to='reports')),
                ('link_QAServer', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('jira', models.TextField(blank=True, null=True)),
                ('parameters', models.CharField(blank=True, max_length=200, null=True)),
                ('approvedBy', models.CharField(blank=True, max_length=64, null=True)),
                ('datapack', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reports.datapack')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reports.environment')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tester', to='reports.tester')),
                ('testing_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reports.testingtype')),
            ],
        ),
        migrations.AddField(
            model_name='datapack',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reports.language'),
        ),
        migrations.AddField(
            model_name='datapack',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reports.topic'),
        ),
    ]
