# Generated by Django 4.0.5 on 2022-07-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='product',
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reports.environment'),
        ),
        migrations.AlterField(
            model_name='testingtype',
            name='name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
