# Generated by Django 4.0.5 on 2022-07-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_product_alter_environment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_submit',
            field=models.DateField(auto_now=True),
        ),
    ]
