# Generated by Django 4.0.5 on 2022-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_date_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_report',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='Nuance/'),
        ),
    ]
