# Generated by Django 4.0.5 on 2022-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_file_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_report',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='reports'),
        ),
    ]
