# Generated by Django 4.0.5 on 2022-08-17 18:23

from django.db import migrations, models
import reports.utils.backend


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_file_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='report',
            name='file_report',
            field=models.FileField(blank=True, null=True, upload_to=reports.utils.backend.get_upload_to),
        ),
    ]
