# Generated by Django 4.0.5 on 2022-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_delete_document_alter_report_file_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.TextField(choices=[('', ''), ('Pass', 'Pass'), ('Fail', 'Fail')], default=''),
        ),
    ]
