# Generated by Django 4.0.5 on 2022-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.TextField(choices=[('', 'None'), ('Pass', 'Pass'), ('Fail', 'Fail')], default=''),
        ),
    ]
