# Generated by Django 4.0.5 on 2022-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_datapack_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.TextField(choices=[('Pending Approval', 'Pending Approval'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Pending Approval'),
        ),
    ]
