# Generated by Django 4.0.5 on 2022-10-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tests_run',
            field=models.ManyToManyField(to='reports.testingtype'),
        ),
    ]
