# Generated by Django 4.0.5 on 2022-10-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_topic_tests_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='parameters',
        ),
    ]
