# Generated by Django 4.0.5 on 2022-11-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0012_remove_report_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
