# Generated by Django 4.0.5 on 2023-02-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_report_tester_delete_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accuracy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
