# Generated by Django 4.0.5 on 2023-03-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accuracy',
            field=models.TextField(choices=[('n/a', 'n/a'), ('nadp', 'nadp'), ('ndp', 'ndp')], default='n/a'),
        ),
    ]
